### ISSUE TITLE
[Proposal] Merge Community.VisualStudio.Toolkit and Clide

### ISSUE THREAD

**Issue by workgroupengineering** [clariuslabs/clide#171]
Thanks for this toolkit and the time invested on it.

On github there is another toolkit that helps in the development of Visual Studio extensions, Clide. It would be nice to merge the features of Community.VisualStudio.Toolkit and Clide.

Reference madskristensen/Community.VisualStudio.Toolkit#26

**Comment by kzu** [comment]
Since the linked repo is archived, I don't see a point here :)
