### ISSUE TITLE
Does clide inject Component's into VS extension points?

### ISSUE THREAD

**Issue by ghost** [clariuslabs/clide#24]
Modified IntegrationPackage\Adornment.cs:

[ExportMetadata("IsClide", true)]
[Export(typeof(IWpfTextViewCreationListener))]
[ContentType("text")]
[TextViewRole(PredefinedTextViewRoles.Document)]
public sealed class TextAdornment1Factory : IWpfTextViewCreationListener
{
    private IServiceProvider services;

    [ImportingConstructor]
    public TextAdornment1Factory([Import(Constants.ShellContractName)] IServiceProvider services, Foo foo)
    {
        this.services = services;
    }

    public void TextViewCreated(IWpfTextView textView)
    {
        Debug.Assert(Clide.DevEnv.Get(services) != null);
    }
}

[Component] public class Foo { }

This seems to cause a silent failure - the Export is never loaded by Visual Studio. Is injecting components into visual studio extension points supported?

**Comment by kzu** [comment]
Nop, it's not supported. Clide components can consume VS services though.
